### PR TITLE
feat(package): add popover directive to public api

### LINKED ISSUE #229: Can not resolve popover.directive on import
The popover.directive is not importable to a component. It would be useful to do so because of the ViewChild selection.

Usage:

```ts
import { PopoverDirective } from 'iwerk-angular-ui/app/ui/popover/popover.directive';
[...]
class ExampleClass {
  @ViewChild(PopoverDirective)
  elementReference: ElementRef<HTMLElement>;
}
```

The error message is

> Can't resolve 'iwerk-angular-ui/app/ui/popover/popover.directive'

Project dependencies and versions are:

```
"dependencies": {
  "@angular/animations": "^7.0.0",
  "@angular/common": "^7.0.0",
  "@angular/compiler": "^7.0.0",
  "@angular/core": "^7.0.0",
  "@angular/forms": "^7.0.0",
  "@angular/http": "^7.0.0",
  "@angular/platform-browser": "^7.0.0",
  "@angular/platform-browser-dynamic": "^7.0.0",
  "@angular/router": "^7.0.0",
  "iwerk-angular-ui": "^5.0.1"
}
```

### PR DESCRIPTION
**Pull request by ngfelixl**
Closes #229.

### CODE REVIEW

**Comment by kevinmerckx** [comment]
@ngfelixl aren't you in the github team??

**Comment by ngfelixl** [comment]
Ah sure, I am. Next time I will push the features directly to this repo.

**Comment by kevinmerckx** [comment]
Np

**Pull request merged**
